---
- hosts: localhost
  become: yes
  vars:
    region: "eu-west-1"
   
  tasks:
  - name: create EC2 instance
    ec2_instance:
      name: "server1"
      region: "{{ region }}"
      instance_type: t2.micro
      key_name: "ec2-ireland"
      security_group: ssh-http
      image_id: ami-040ba9174949f6de4
      tags:
        ansible: webserver