---
- hosts: localhost
  vars:
    region: eu-west-1
    cidr: "10.0.0.0/16"
    zone1: a
    zone2: b
   
  tasks:
  - name: create VPC
    ec2_vpc_net:
      name: Wordpress2
      cidr_block: "{{ cidr }}"
      region: "{{ region }}"
      state: present
      tags:
        project: wordpress_ansible
    register: network      

  - name: create subnet public_a
    ec2_vpc_subnet:
      region: "{{ region }}"
      state: present
      cidr: "{{ cidr }}"
      az: "{{ region }}{{ zone1 }}"
      vpc_id: "{{ network.vpc.id }}"
      resource_tags:
        project: wordpress_ansible
        Name: "public_{{ zone1 }}"
    register: subnet-public-a

  - name: create subnet public_b
    ec2_vpc_subnet:
      region: "{{ region }}"
      state: present
      cidr: "{{ cidr }}"
      az: "{{ region }}{{ zone2 }}"
      vpc_id: "{{ network.vpc.id }}"
      resource_tags:
        project: wordpress_ansible
        Name: "public_{{ zone2 }}"
    register: subnet-public-b