---
- hosts: localhost
  vars:
    vpc_name: "Wordpress2"
    project_name: "wordpress_ansible"
    region: "eu-west-1"
    cidr: "10.0.0.0/16"
    cidr_public_a: "10.0.1.0/24"
    cidr_public_b: "10.0.4.0/24"
    cidr_web_a: "10.0.2.0/24"
    cidr_web_b: "10.0.5.0/24"
    cidr_data_a: "10.0.3.0/24"
    cidr_data_b: "10.0.6.0/24"
    zone1: "a"
    zone2: "b"
   
  tasks:
  - name: create VPC
    ec2_vpc_net:
      name: "{{ vpc_name }}"
      cidr_block: "{{ cidr }}"
      region: "{{ region }}"
      state: present
      tags:
        project: "{{ project_name }}"
    register: network      

  - name: create subnet public_a
    ec2_vpc_subnet:
      region: "{{ region }}"
      state: present
      cidr: "{{ cidr_public_a }}"
      az: "{{ region }}{{ zone1 }}"
      vpc_id: "{{ network.vpc.id }}"
      resource_tags:
        project: "{{ project_name }}"
        Name: "public_az_{{ zone1 }}"
    register: subnetpublica

  - name: create subnet public_b
    ec2_vpc_subnet:
      region: "{{ region }}"
      state: present
      cidr: "{{ cidr_public_b }}"
      az: "{{ region }}{{ zone2 }}"
      vpc_id: "{{ network.vpc.id }}"
      resource_tags:
        project: "{{ project_name }}"
        Name: "public_az_{{ zone2 }}"
    register: subnetpublicb

  - name: create subnet web_a
    ec2_vpc_subnet:
      region: "{{ region }}"
      state: present
      cidr: "{{ cidr_web_a }}"
      az: "{{ region }}{{ zone1 }}"
      vpc_id: "{{ network.vpc.id }}"
      resource_tags:
        project: "{{ project_name }}"
        Name: "web_az_{{ zone1 }}"
    register: subnetweba

  - name: create subnet web_b
    ec2_vpc_subnet:
      region: "{{ region }}"
      state: present
      cidr: "{{ cidr_web_b }}"
      az: "{{ region }}{{ zone2 }}"
      vpc_id: "{{ network.vpc.id }}"
      resource_tags:
        project: "{{ project_name }}"
        Name: "web_az_{{ zone2 }}"
    register: subnetwebb

  - name: create subnet data_a
    ec2_vpc_subnet:
      region: "{{ region }}"
      state: present
      cidr: "{{ cidr_data_a }}"
      az: "{{ region }}{{ zone1 }}"
      vpc_id: "{{ network.vpc.id }}"
      resource_tags:
        project: "{{ project_name }}"
        Name: "data_az_{{ zone1 }}"
    register: subnetdataa

  - name: create subnet data_b
    ec2_vpc_subnet:
      region: "{{ region }}"
      state: present
      cidr: "{{ cidr_data_b }}"
      az: "{{ region }}{{ zone2 }}"
      vpc_id: "{{ network.vpc.id }}"
      resource_tags:
        project: "{{ project_name }}"
        Name: "data_az_{{ zone2 }}"
    register: subnetdatab

  - name: vpc internet gateway
    ec2_vpc_igw:
      region: "{{ region }}"
      vpc_id: "{{ network.vpc.id }}"
      state: present
      tags:
        project: "{{ project_name }}"
    register: igw

  - name: Create new nat gateway public a
    ec2_vpc_nat_gateway:
      state: present
      subnet_id: "{{ subnetpublica.subnet.id }}"
      if_exist_do_not_create: true
      wait: yes
      region: "{{ region }}"
    register: natgatewaypublica

  - name: Create new nat gateway public b
    ec2_vpc_nat_gateway:
      state: present
      subnet_id: "{{ subnetpublicb.subnet.id }}"
      if_exist_do_not_create: true
      wait: yes
      region: "{{ region }}"
    register: natgatewaypublicb

  - name: Get Route table
    ec2_vpc_route_table_facts:
      region: "{{ region }}"
      filters:
        vpc-id: "{{ network.vpc.id }}"
    register: route

  - name: Debug
    debug:
      msg: "{{ route.route_tables.route_table_id }}"