---
- hosts: all
  become: true
  vars:

  tasks:
  - name: install httpd
    ansible.builtin.yum:
      name:
        - httpd
        - git
      state: latest

  - name: Git Clone
    git:
      repo: "https://github.com/jesperberth/ansibleweb.git"
      dest: /var/www/html

  - name: start httpd
    service:
      name: httpd
      state: started
