---
- hosts: localhost
  vars:
    region: eu-west-1
    cidr: "10.0.0.0/16"
    cidr_public_a: "10.0.1.0/24"
    cidr_public_b: "10.0.4.0/24"
    cidr_web_a: "10.0.2.0/24"
    cidr_web_b: "10.0.5.0/24"
    cidr_data_a: "10.0.3.0/24"
    cidr_data_b: "10.0.6.0/24"
    zone1: a
    zone2: b
   
  tasks:
  - name: create VPC
    ec2_vpc_net:
      name: Wordpress2
      cidr_block: "{{ cidr }}"
      region: "{{ region }}"
      state: present
      tags:
        project: wordpress_ansible
    register: network      

  - name: create subnet public_a
    ec2_vpc_subnet:
      region: "{{ region }}"
      state: present
      cidr: "{{ cidr_public_a }}"
      az: "{{ region }}{{ zone1 }}"
      vpc_id: "{{ network.vpc.id }}"
      resource_tags:
        project: wordpress_ansible
        Name: "public_az_{{ zone1 }}"
    register: subnet-public-a

  - name: create subnet public_b
    ec2_vpc_subnet:
      region: "{{ region }}"
      state: present
      cidr: "{{ cidr_public_b }}"
      az: "{{ region }}{{ zone2 }}"
      vpc_id: "{{ network.vpc.id }}"
      resource_tags:
        project: wordpress_ansible
        Name: "public_az_{{ zone2 }}"
    register: subnet-public-b

  - name: create subnet web_a
    ec2_vpc_subnet:
      region: "{{ region }}"
      state: present
      cidr: "{{ cidr_web_a }}"
      az: "{{ region }}{{ zone1 }}"
      vpc_id: "{{ network.vpc.id }}"
      resource_tags:
        project: wordpress_ansible
        Name: "web_az_{{ zone1 }}"
    register: subnet-web-a

  - name: create subnet web_b
    ec2_vpc_subnet:
      region: "{{ region }}"
      state: present
      cidr: "{{ cidr_web_b }}"
      az: "{{ region }}{{ zone2 }}"
      vpc_id: "{{ network.vpc.id }}"
      resource_tags:
        project: wordpress_ansible
        Name: "web_az_{{ zone2 }}"
    register: subnet-web-b

  - name: create subnet data_a
    ec2_vpc_subnet:
      region: "{{ region }}"
      state: present
      cidr: "{{ cidr_data_a }}"
      az: "{{ region }}{{ zone1 }}"
      vpc_id: "{{ network.vpc.id }}"
      resource_tags:
        project: wordpress_ansible
        Name: "data_az_{{ zone1 }}"
    register: subnet-data-a

  - name: create subnet data_b
    ec2_vpc_subnet:
      region: "{{ region }}"
      state: present
      cidr: "{{ cidr_data_b }}"
      az: "{{ region }}{{ zone2 }}"
      vpc_id: "{{ network.vpc.id }}"
      resource_tags:
        project: wordpress_ansible
        Name: "data_az_{{ zone2 }}"
    register: subnet-data-b

  - name: vpc internet gateway
    ec2_vpc_igw:
      region: "{{ region }}"
      vpc_id: "{{ network.vpc.id }}"
      state: present
      tags:
        project: wordpress_ansible
    register: igw

  - name: allocate eip az a
    ec2_eip:
      region: "{{ region }}"
      in_vpc: yes
    register: eip_a

  - name: allocate eip az b
    ec2_eip:
      region: "{{ region }}"
      in_vpc: yes
    register: eip_b

  - name: test
    debug:
      msg: "{{ subnet-public-a.subnet.id }}"

  - name: Create new nat gateway
    ec2_vpc_nat_gateway:
      state: present
      subnet_id: "{{ subnet-public-a.subnet.id }}"
      eip_address: "{{ eip_a.public_ip }}"
      wait: yes
      region: "{{ region }}"
    register: nat_gateway_public_a