---
- hosts: "{{ vm_name }}"
  remote_user: root
  vars:
    gitrepo: https://github.com/jesperberth/tomato-monkey.git
    
  tasks:
    - name: ensure httpd is installed
      yum:
       name: httpd
       state: latest

    - name: ensure httpd is enabled
      service:
        name: httpd
        enabled: yes

    - name: Install git
      yum:
        name: git
        state: latest

    - name: Download Website from Github  
      git:
        repo: "{{ gitrepo }}"
        dest: "/var/www/html"

    - name: ensure httpd is running
      service:
       name: httpd
       state: started

    - name: Firewall Allow Http
      firewalld:
        zone: public
        service: http
        permanent: true
        state: enabled
      notify: reload firewall

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted

    - name: reload firewall
      systemd:
        name: firewalld
        state: reloaded