---
- name: OCI Webserver Network
  hosts: localhost
  vars:
    compartmentid: "ocid1.tenancy.oc1..aaaaaaaawkmnjfryshdufax2ar4h4x7ijbnvkcy3kgwun2pcbq7vj6k3xfbq"
    vcn_cidr_block: "10.0.0.0/16"
    vcn_name: "WebsiteNetwork"
    vcn_dns_label: "website"
    subnet_dns_label: "webserver"
    webserver_subnet_name: "webserver"
    webserver_subnet_cidr: "10.0.0.0/24"
  
  tasks:
  - name: Create a VCN
    oci_vcn:
      compartment_id: "{{ compartmentid }}"
      display_name: "{{ vcn_name }}"
      cidr_block: "{{ vcn_cidr_block }}"
      dns_label: "{{ vcn_dns_label }}"
    register: vcnresult
  - debug:
      msg: "{{ vcnresult }}"
  - set_fact:
      vcn_id: "{{ vcnresult.vcn.id }}"
      default_route_table_id: "{{ vcnresult.vcn.default_route_table_id }}"
      default_security_list_id: "{{ vcnresult.vcn.default_security_list_id }}"