---
- name: OCI Webserver Network
  hosts: localhost
  vars:
    compartmentid: "ocid1.tenancy.oc1..aaaaaaaawkmnjfryshdufax2ar4h4x7ijbnvkcy3kgwun2pcbq7vj6k3xfbq"
    vcn_cidr_block: "10.0.0.0/16"
    vcn_name: "WebsiteNetwork"
    vcn_dns_label: "website"
    subnet_dns_label: "webserver"
    webserver_subnet_name: "webserver"
    webserver_subnet_cidr: "10.0.0.0/24"
  
  tasks:
  - name: api_user
    debug: msg="{{ api_user }}"

  - name: api_user_fingerprint
    debug: msg="{{ api_user_fingerprint }}"

  - name: region
    debug: msg="{{ region }}"

  - name: tenancy
    debug: msg="{{ tenancy }}"

  - name: key_file
    debug: msg="{{ api_user_key_file }}"

  - name: config_file
    debug: msg="{{ config_file_location }}"
    
  - name: Create a VCN
    oci_vcn:
      config_file_location: "{{ config_file_location }}"
      compartment_id: "{{ compartmentid }}"
      display_name: "{{ vcn_name }}"
      cidr_block: "{{ vcn_cidr_block }}"
      dns_label: "{{ vcn_dns_label }}"
      api_user: "{{ api_user }}"
      api_user_fingerprint: "{{ api_user_fingerprint }}"
      api_user_key_file: "{{ api_user_key_file }}"
      region: "{{ region }}"
      tenancy: "{{ tenancy }}"
    register: vcnresult
  - debug:
      msg: "{{ vcnresult }}"
  - set_fact:
      vcn_id: "{{ vcnresult.vcn.id }}"
      default_route_table_id: "{{ vcnresult.vcn.default_route_table_id }}"
      default_security_list_id: "{{ vcnresult.vcn.default_security_list_id }}"