---
- name: Create VM on RHV
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    datacenter: Democenter
    cluster: Arrowdemo
    #template: Win2019
    #vm_memory: 8GiB
    #cpu_cores: 2
    #network: "ovirtmgmt"
    #vm_name: test.redhat.local

  pre_tasks:
    - name: Login to oVirt
      ovirt_auth:

  tasks:
  - name: Create and run VM from template
    ovirt_vm:
     auth: "{{ ovirt_auth }}"
     name: "{{ vm_name }}.{{ vm_domain }}"
     template: "{{ template }}"
     cluster: "{{ cluster }}"
     memory: "{{ vm_memory }}"
     cpu_cores: "{{ cpu_cores }}"
     high_availability: true
     state: running
     nics:
      - name: nic1
        profile_name: "{{ network }}"
        network_name: "{{ network }}"
     sysprep:
       host_name: "{{ vm_name }}"
       user_name: "{{ vm_user }}"
       root_password: "{{ vm_password }}"
     wait: yes

  - name: Tag VM
    ovirt_tag:
      name: ansible_windows_group1
      vms: "{{ vm_name }}.{{ vm_domain }}"
  
  - name: Wait for vm
    pause:
      minutes: 5

  post_tasks:
    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
