---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      name: testvm_2
      template: _TEMP_centos7_x64
      disk:
      - size_gb: 30
        type: thin
        datastore: St01_ZFS_LUN05
      networks:
      - name: "125 - redhat.local"
      datacenter: Arrowdemo
      folder: "/Red Hat"
      state: poweredon
      cluster: Democluster01
      wait_for_ip_address: yes
    register: newvm
    
