---
- name: Enable Exchange Maintenance Mode
  hosts: "{{ hosts }}"
  tasks:
    - name: Enable Exchange Maintenance Mode
      win_shell: |
        Get-ServerComponentState -Identity exch01.exch.arrowdemo.dk
      register: shell_out
      debug: 
        var: shell_out