---
- name: Enable Exchange Maintenance Mode
  hosts: "{{ hosts }}"
  tasks:
    - name: Enable Exchange Maintenance Mode
      win_dsc:
        resource_name: xExchMaintenanceMode
        Enabled: True
        Credential:
        Credential_username: "{{ ansible_user }}"
        Credentual_password: "{{ ansible_password }}"