---
- name: Run Windows Update
  hosts: Windows
  tasks:
    - name: Windows Update
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        reboot: yes
      register:  installed_update_count
    - debug: var=installed_update_count