---
- name: Exit Exchange Maintenance Mode
  hosts: "{{ maintenance }}"
  become: yes
  tasks:
    - name: Exit Exchange Maintenance Mode
      win_shell: |
        Add-PSSnapin Microsoft.Exchange.Management.PowerShell.SnapIn
        Set-ServerComponentState "{{ maintenance }}" -Component ServerWideOffline -State Active -Requester Maintenance
        Resume-ClusterNode "{{ maintenance }}"
        Set-MailboxServer "{{ maintenance }}" -DatabaseCopyActivationDisabledAndMoveNow $False
        Set-MailboxServer "{{ maintenance }}" -DatabaseCopyAutoActivationPolicy Unrestricted
        Set-ServerComponentState "{{ maintenance }}" -Component HubTransport -State Active -Requester Maintenance
