---
- name: Enable Exchange Maintenance Mode
  hosts: "{{ maintenance }}"
  become: yes
  become_user: administrator@exch.arrowdemo.dk
  tasks:
    - name: Enable Exchange Maintenance Mode
      win_shell: |
        Add-PSSnapin Microsoft.Exchange.Management.PowerShell.SnapIn
        Set-ServerComponentState "{{ maintenance }}" -Component HubTransport -State Draining -Requester Maintenance
        Restart-Service MSExchangeTransport
        Restart-Service MSExchangeFrontEndTransport
        Redirect-Message -Server "{{ maintenance }}" -Target "{{ takeover }}"
        Suspend-ClusterNode "{{ maintenance }}"
        Set-MailboxServer "{{ maintenance }}" -DatabaseCopyActivationDisabledAndMoveNow $True
        Set-MailboxServer "{{ maintenance }}" -DatabaseCopyAutoActivationPolicy Blocked
        Set-ServerComponentState "{{ maintenance }}" -Component ServerWideOffline -State Inactive -Requester Maintenance