---
- name: Enable Exchange Maintenance Mode
  hosts: "{{ host }}"
  become: yes
  become_user: administrator@exch.arrowdemo.dk
  tasks:
    - name: Enable Exchange Maintenance Mode
      win_shell: |
