---
- name: Enable Exchange Maintenance Mode
  hosts: "{{ hosts }}"
  become: yes
  become_user: administrator@exch.arrowdemo.dk
  tasks:
    - name: Enable Exchange Maintenance Mode
      win_shell: |
        Add-PSSnapin Microsoft.Exchange.Management.PowerShell.SnapIn
        Set-ServerComponentState "{{ hosts }}" -Component HubTransport -State Draining -Requester Maintenance
