---
- name: Run Windows Update
  hosts: Windows
  tasks:
    - name: Windows Update
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
      register:  update_result
    - name: reboot
      win_reboot:
        when: update_result.reboot_required
        reboot_timeout: 3600
    - debug: var=update_result